from abc import ABC, abstractmethod

class Estrategia(ABC):
    def __init__(self, qdef=2): self.qdef = int(qdef)
    @abstractmethod
    def add(self, p): ...
    @abstractmethod
    def elegir(self, actual): ...
    @abstractmethod
    def pre_tick(self, actual): ...
    @abstractmethod
    def post_tick(self, actual): ...
    @abstractmethod
    def reinsertar(self, p): ...
    @abstractmethod
    def peek_ready(self): ...
    @abstractmethod
    def dump_ready(self): ...
